function [fitresult, gof] = create2Dfit(x, y, G)
%CREATEFIT1(X,Y,G)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Input : y
%      Z Output: G
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Apr-2016 18:19:58


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( x, y, G );

[Y0, X0] = find(ismember(G, max(max(G))),size(G,3));
x0 = x(X0);
y0 = y(Y0);

[~,ex]=max(zData);

% Set up fittype and options.
ft = fittype( 'a*(exp(-((((x-x0)^2)+((y-y0)^2)))/(c^2)))+b', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf x0 y0];
opts.StartPoint = [0.165 0.034 2.1 x0 y0];
opts.Upper = [Inf Inf Inf x0 y0];
opts.Exclude= [ex];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% %Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'untitled fit 1', 'G vs. x, y', 'Location', 'NorthEast' );
% % Label axes
% xlabel x
% ylabel y
% zlabel G
% grid on


